AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template that deploys Athena-specific resources for OpenTelemetry Collector, including Glue Database, Crawler, SNS/SQS notifications, and Lambda UDF
Metadata:
  License: >
    Copyright 2025 Monte Carlo Data, Inc.

    The Software contained herein (the "Software") is the intellectual property of Monte Carlo Data, Inc. ("Licensor"),
    and Licensor retains all intellectual property rights in the Software, including any and all derivatives, changes and
    improvements thereto. Only customers who have entered into a commercial agreement with Licensor for use or
    purchase of the Software ("Licensee") are licensed or otherwise authorized to use the Software, and any Licensee
    agrees that it obtains no copyright or other intellectual property rights to the Software, except for the license
    expressly granted below or in accordance with the terms of their commercial agreement with Licensor (the
    "Agreement"). Subject to the terms and conditions of the Agreement, Licensor grants Licensee a non-exclusive,
    non-transferable, non-sublicensable, revocable, limited right and license to use the Software, in each case solely
    internally within Licensee's organization for non-commercial purposes and only in connection with the service
    provided by Licensor pursuant to the Agreement, and in object code form only. Without Licensor's express prior
    written consent, Licensee may not, directly or indirectly, (i) distribute the Software, any portion thereof, or any
    modifications, enhancements, or derivative works of any of the foregoing (collectively, the "Derivatives") to any
    third party, (ii) license, market, sell, offer for sale or otherwise attempt to commercialize any Software, Derivatives,
    or portions thereof, (iii) use the Software, Derivatives, or any portion thereof for the benefit of any third party, (iv)
    use the Software, Derivatives, or any portion thereof in any manner or with respect to any commercial activity
    which competes, or is reasonably likely to compete, with any business that Licensor conducts, proposes to conduct
    or demonstrably anticipates conducting, at any time; or (v) seek any patent or other intellectual property rights or
    protections over or in connection with any Software of Derivatives.

Parameters:
  TelemetryDataBucketArn:
    Type: String
    Description: ARN of the S3 bucket containing telemetry data
    AllowedPattern: '^arn:aws:s3:::.*$'
    ConstraintDescription: Must be a valid S3 bucket ARN

  SNSTopicArn:
    Type: String
    Description: ARN of an existing SNS topic to use for notifications. If left empty, a new SNS topic will be created.
    Default: ""
    AllowedPattern: '^(|arn:aws:sns:[^:]+:[0-9]{12}:[^:]+)$'
    ConstraintDescription: Must be either empty or a valid SNS topic ARN

  LambdaUDFImageUri:
    Type: String
    Description: URI of the Lambda UDF container image
    Default: "752656882040.dkr.ecr.us-east-1.amazonaws.com/mcd-otel-aws-athena-lambda-udf:latest"

  LambdaUDFTimeout:
    Type: Number
    Description: Timeout in seconds for the Lambda UDF function
    Default: 300
    MinValue: 1
    MaxValue: 900

  LambdaUDFMemorySize:
    Type: Number
    Description: Memory size in MB for the Lambda UDF function
    Default: 512
    MinValue: 128
    MaxValue: 10240

Conditions:
  UseExistingSNS: !Not [!Equals [!Ref SNSTopicArn, ""]]
  CreateSNS: !Equals [!Ref SNSTopicArn, ""]

Resources:
  # Glue Classifier
  GrokClassifier:
    Type: AWS::Glue::Classifier
    Properties:
      GrokClassifier:
        Classification: grok
        GrokPattern: "%{GREEDYDATA:value}"

  # SNS Topic (only if not provided)
  TelemetryNotificationsTopic:
    Type: AWS::SNS::Topic
    Condition: CreateSNS
    Properties:
      TopicName: !Sub "${AWS::StackName}-telemetry-notifications"
      Tags:
        - Key: Service
          Value: "mcd-otel-collector"
        - Key: Provider
          Value: "monte-carlo"

  # SNS Topic Policy to allow S3 to publish (only if SNS topic was created)
  TelemetryNotificationsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Condition: CreateSNS
    Properties:
      Topics:
        - !Ref TelemetryNotificationsTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: SNS:Publish
            Resource: !Ref TelemetryNotificationsTopic
            Condition:
              ArnLike:
                aws:SourceArn: !Ref TelemetryDataBucketArn

  # SQS Queue
  CrawlerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-glue-crawler-queue"
      MessageRetentionPeriod: 1209600  # 14 days
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      Tags:
        - Key: Service
          Value: "mcd-otel-collector"
        - Key: Provider
          Value: "monte-carlo"

  # SQS Queue Policy for SNS subscription
  CrawlerQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref CrawlerQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt CrawlerQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !If
                  - UseExistingSNS
                  - !Ref SNSTopicArn
                  - !Ref TelemetryNotificationsTopic
          - Effect: Allow
            Principal:
              AWS: !GetAtt GlueCrawlerRole.Arn
            Action:
              - sqs:DeleteMessage
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
              - sqs:GetQueueAttributes
              - sqs:SetQueueAttributes
              - sqs:PurgeQueue
            Resource: !GetAtt CrawlerQueue.Arn

  # SNS Topic Subscription
  SQSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !If
        - UseExistingSNS
        - !Ref SNSTopicArn
        - !Ref TelemetryNotificationsTopic
      Protocol: sqs
      Endpoint: !GetAtt CrawlerQueue.Arn

  # IAM Role for Glue Crawler
  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-glue-crawler-role"
      Path: "/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-glue-crawler-s3-policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Ref TelemetryDataBucketArn
                  - !Sub "${TelemetryDataBucketArn}/*"
        - PolicyName: !Sub "${AWS::StackName}-glue-crawler-sqs-policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - sqs:DeleteMessage
                  - sqs:GetQueueUrl
                  - sqs:ReceiveMessage
                  - sqs:GetQueueAttributes
                  - sqs:SetQueueAttributes
                  - sqs:PurgeQueue
                Resource: !GetAtt CrawlerQueue.Arn
      Tags:
        - Key: Service
          Value: "mcd-otel-collector"
        - Key: Provider
          Value: "monte-carlo"

  # Glue Database
  TelemetryDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub "${AWS::StackName}-telemetry-db"
        Description: "Database for OpenTelemetry telemetry data"

  # Glue Crawler
  TelemetryCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub "${AWS::StackName}-telemetry-crawler"
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref TelemetryDatabase
      Classifiers:
        - !Ref GrokClassifier
      Targets:
        S3Targets:
          - Path: !Sub 
              - "s3://${BucketName}/mcd/otel-collector/traces/"
              - BucketName: !Select [5, !Split [":", !Ref TelemetryDataBucketArn]]
            EventQueueArn: !GetAtt CrawlerQueue.Arn
      SchemaChangePolicy:
        DeleteBehavior: LOG
        UpdateBehavior: UPDATE_IN_DATABASE
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_EVENT_MODE
      Schedule:
        ScheduleExpression: "cron(*/30 * * * ? *)"
      Configuration: |
        {
          "Version": 1.0,
          "CrawlerOutput": {
            "Tables": {
              "AddOrUpdateBehavior": "MergeNewColumns",
              "TableThreshold": 1
            }
          },
          "Grouping": {
            "TableGroupingPolicy": "CombineCompatibleSchemas"
          }
        }
      Tags:
        - Key: Service
          Value: "mcd-otel-collector"
        - Key: Provider
          Value: "monte-carlo"

  # IAM Role for Lambda UDF
  LambdaUDFRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-lambda-udf-role"
      Path: "/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-lambda-udf-bedrock-policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowInvokeBedrock
                Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource:
                  - "arn:aws:bedrock:*::foundation-model/anthropic.claude-*"
                  - "arn:aws:bedrock:*:*:inference-profile/*anthropic.claude-*"
      Tags:
        - Key: Service
          Value: "mcd-otel-collector"
        - Key: Provider
          Value: "monte-carlo"

  # Lambda Function for Athena UDF
  AthenaUDF:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: mcd-agent-observability-bedrock-udf-2
      Role: !GetAtt LambdaUDFRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Ref LambdaUDFImageUri
      Timeout: !Ref LambdaUDFTimeout
      MemorySize: !Ref LambdaUDFMemorySize
      ImageConfig:
        Command:
          - handler.lambda_handler
      Tags:
        - Key: Service
          Value: "mcd-otel-collector"
        - Key: Provider
          Value: "monte-carlo"

Outputs:
  GlueDatabaseName:
    Description: Name of the Glue database
    Value: !Ref TelemetryDatabase
    Export:
      Name: !Sub "${AWS::StackName}-GlueDatabaseName"

  GlueCrawlerName:
    Description: Name of the Glue crawler
    Value: !Ref TelemetryCrawler
    Export:
      Name: !Sub "${AWS::StackName}-GlueCrawlerName"

  SNSTopicArn:
    Description: ARN of the SNS topic used for notifications
    Value: !If
      - UseExistingSNS
      - !Ref SNSTopicArn
      - !Ref TelemetryNotificationsTopic
    Export:
      Name: !Sub "${AWS::StackName}-SNSTopicArn"

  SQSQueueArn:
    Description: ARN of the SQS queue
    Value: !GetAtt CrawlerQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SQSQueueArn"

  LambdaUDFFunctionName:
    Description: Name of the Lambda UDF function
    Value: !Ref AthenaUDF
    Export:
      Name: !Sub "${AWS::StackName}-LambdaUDFFunctionName"

  LambdaUDFFunctionArn:
    Description: ARN of the Lambda UDF function
    Value: !GetAtt AthenaUDF.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaUDFFunctionArn"
